- name: install
  yum: name={{ item }} state=present
  with_items:
    - "{{ elasticsearch_rpm_url }}"
    - java-1.8.0-openjdk

- name: chkconfig on
  shell: chkconfig elasticsearch on

- include: configure.yml

- name: elasticsearch restart
  shell: /etc/init.d/elasticsearch restart
